#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts" / "openapi.yaml"
FRONTEND_TYPES = ROOT / "frontend" / "src" / "shared" / "api" / "generated" / "types.ts"
FRONTEND_ALIASES = ROOT / "frontend" / "src" / "shared" / "api" / "types.ts"


def load_contract() -> dict[str, Any]:
    return yaml.safe_load(CONTRACT.read_text(encoding="utf-8"))


def schema_names(spec: dict[str, Any]) -> list[str]:
    return sorted((spec.get("components") or {}).get("schemas") or {})


def alias_text(spec: dict[str, Any]) -> str:
    lines = [
        "// This file was auto-generated by scripts/generate_openapi.py.",
        "// Do not make direct changes to this file.",
        "",
        "import type { components } from './generated/types';",
        "",
    ]
    for name in schema_names(spec):
        lines.append(f"export type {name} = components['schemas']['{name}'];")
    lines.append("")
    return "\n".join(lines)


def run_openapi_typescript(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "npm",
            "--prefix",
            "frontend",
            "exec",
            "openapi-typescript",
            "--",
            str(CONTRACT),
            "-o",
            str(output if output.is_absolute() else output.relative_to(ROOT)),
        ],
        cwd=ROOT,
        check=True,
    )


def backend_contract_matches(spec: dict[str, Any]) -> bool:
    sys.path.insert(0, str(ROOT / "backend" / "src"))
    from agent_context_engine.interfaces.http.openapi import openapi_spec

    openapi_spec.cache_clear()
    return openapi_spec() == spec


def write_outputs() -> int:
    spec = load_contract()
    run_openapi_typescript(FRONTEND_TYPES)
    FRONTEND_ALIASES.write_text(alias_text(spec), encoding="utf-8")
    return 0


def check_outputs() -> int:
    spec = load_contract()
    failures: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        tmp_types = Path(tmp) / "types.ts"
        run_openapi_typescript(tmp_types)
        if FRONTEND_TYPES.read_text(encoding="utf-8") != tmp_types.read_text(encoding="utf-8"):
            failures.append(f"stale generated frontend types: {FRONTEND_TYPES.relative_to(ROOT)}")
    expected_aliases = alias_text(spec)
    if not FRONTEND_ALIASES.exists() or FRONTEND_ALIASES.read_text(encoding="utf-8") != expected_aliases:
        failures.append(f"stale generated frontend aliases: {FRONTEND_ALIASES.relative_to(ROOT)}")
    if not backend_contract_matches(spec):
        failures.append("backend openapi_spec() does not match contracts/openapi.yaml")
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        print("run: python3 scripts/generate_openapi.py --write", file=sys.stderr)
        return 1
    print("openapi generated artifacts are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_outputs() if args.write else check_outputs()


if __name__ == "__main__":
    raise SystemExit(main())
